<a href="https://colab.research.google.com/github/Dominic2681998/Data_Science/blob/main/startup__multilinear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
  
dataset = pd.read_csv('startups.csv')
dataset.head()

R&D Spend  Administration  ...     Profit Unnamed: 5
0  165349.20       136897.80  ...  192261.83        NaN
1  162597.70       151377.59  ...  191792.06        NaN
2  153441.51       101145.55  ...  191050.39        NaN
3  144372.41       118671.85  ...  182901.99        NaN
4  142107.34        91391.77  ...  166187.94        NaN

[5 rows x 6 columns]

In [6]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [24]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelEncoder_X = LabelEncoder() 
X[:,3] = labelEncoder_X.fit_transform(X[ : , 3])
X
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X), dtype=np.float)


In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [26]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train) 

LinearRegression()

In [27]:
y_pred = regressor.predict(X_test)
y_test

array([134307.35,  81005.76,  99937.59,  64926.08, 125370.37,  35673.41,
       105733.54, 107404.34,  97427.84, 122776.86, 141585.52, 166187.94,
        89949.14, 152211.77, 182901.99])

In [22]:
y_pred

array([134307.35,  81005.76,  99937.59,  64926.08, 125370.37,  35673.41,
       105733.54, 107404.34,  97427.84, 122776.86, 141585.52, 166187.94,
        89949.14, 152211.77, 182901.99])

In [28]:
from sklearn.metrics import r2_score
print("R2 Score:",r2_score(y_test,y_pred))

R2 Score: 1.0
